name: Depot CI cache disk mount
description: Mount a durable cache disk which supports mult-write and shares content between runs
author: Depot
branding:
  icon: package
  color: gray-dark
runs:
  using: node24
  main: dist/index.js
  post: dist/post.js
inputs:
  path:
    description: |-
      The path to the cache directory to mount.
      Example: '/tmp/cache-disk'
    required: true
  name:
    description: |-
      The name of the cache disk.
      Example: "cache-disk"
    required: true
  write-lock:
    description: |-
      Lock a file or directory for write operations.
    required: false
  debug:
    description: |-
      Enables detailed logging.
    default: false
    required: false
